version: '3.8'

services:
    nginx: 
        image: nginx:latest
        container_name: nginx-4-webapp
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
        - 8080:80
        - 443:443
        depends_on: 
            - webapp
    prometheus:
        image: prom/prometheus
        container_name: prometheus-4-webapp
        volumes:
        - ./prometheus/:/etc/prometheus/
        ports:
        - 9090:9090
        depends_on: 
        - webapp
    node-exporter:
        image: prom/node-exporter:latest
        container_name: node_exporter-4-prometheus
        restart: unless-stopped
        expose:
        - 9100
    grafana:
        image: grafana/grafana
        container_name: grafana-4-webapp
        volumes:
        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
        - grafana-storage:/var/lib/grafana
        ports:
        - 3000:3000
        depends_on: 
        - prometheus
    webapp:
        image: zyl1204/flask-app
        container_name: webapp
    
    #Used nginx, so no need to expose ports.
    #    ports:
    #    - 5000:5000
volumes: 
    grafana-storage: